<?php
    echo'
    <footer>
        <a href="https://maps.google.com?q=A35+Bach+Dang+Street,+Tan+Binh+District,+Ho+Chi+Minh+City,+Viet+Nam"
            target="_blank" class="contact-item">
            <img src="images/light/address.svg" alt="Address Icon" class="light-mode-element contact-icon">
            <img src="images/dark/address.svg" alt="Address Icon" class="dark-mode-element contact-icon">
            <p>A35 Bach Dang Street, Tan Binh District, Ho Chi Minh City, Viet Nam.</p>
        </a>
        <a href="tel:+84387148555" class="contact-item">
            <img src="images/light/phone.svg" alt="Phone Icon" class="light-mode-element contact-icon">
            <img src="images/dark/phone.svg" alt="Phone Icon" class="dark-mode-element contact-icon">
            <p>+84387148555</p>
        </a>
        <a href="mailto:104486332@student.swin.edu.au" class="contact-item">
            <img src="images/light/email.svg" alt="Email Icon" class="light-mode-element contact-icon">
            <img src="images/dark/email.svg" alt="Email Icon" class="dark-mode-element contact-icon">
            <p>104486332@student.swin.edu.au</p>
        </a>
        <p>© 2024 Future Powered Solutions</p>
    </footer>';
?>